apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"auth":"{{ `{{ .auth }}` }}}'
  data:
  - secretKey: auth
    remoteRef:
      key: {{ .Values.dockerHub.authKey }}
  