controller:
  extraArgs: {}
  service:
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/port_80_no_probe_rule: true
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
