externalSecrets:
  version: 1.2.0
  secretStoreName: azure

externalDns:
  version: 1.19.0

cloudflare:
  secretName: cloudflare
  apiTokenKey: api-token

certManager:
  version: v1.19.1
  email: acme@dmmo.io
  server: https://acme-v02.api.letsencrypt.org/directory

haproxy:
  version: 1.47.3

gatewayApi:
  version: v1.4.0

argocd:
  version: 9.2.3

modsecurity:
  version: 4.21.0