apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.14.0
    helm:
        valueObject:
          controller:
            extraArgs: {}
            service:
              ipFamilyPolicy: PreferDualStack
              ipFamilies:
                - IPv4
                - IPv6
              externalTrafficPolicy: Cluster
              annotations:
                service.beta.kubernetes.io/port_80_no_probe_rule: true
                service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx