spec:
  source:
  destination:
    server: https://kubernetes.default.svc

nginx:
  version: "4.14.0"

externalSecrets:
  version: "0.20.4"
  secretStoreName: azure

externalDns:
  version: "1.18.0"

cloudflare:
  secretName: cloudflare
  apiTokenKey: api-token

certManager:
  version: "v1.19.1"

haproxy:
  version: "1.46.0"
