spec:
  source: ssh://git@github.com/mdmsua/tfc.git
  destination:
    server: https://kubernetes.default.svc

nginx:
  version: "4.14.0"

externalSecrets:
  version: "0.20.4"
  secretStoreName: azure

externalDns:
  version: "1.18.0"

cloudflare:
  secretName: cloudflare
  apiTokenKey: api-token

certManager:
  version: "v1.19.1"
  acme:
    email: acme@dmmo.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory

haproxy:
  version: "1.46.0"

gatewayApi:
  version: "v1.4.0"
